### ISSUE TITLE
Refactor - actor/process based model for plugins

### ISSUE THREAD

**Issue by Marak** [nodejitsu/kohai#7]
Each plugin should run as a separate process that connects to the core irc bot via dnode. This will allow for us to take services up and down without taking down the main bot.

This should be simple re-factor, but we might want to bring in @substack to assist.

**Comment by indexzero** [comment]
+1 to the refactor. -1 to multiple processes. Why can't each module just expose `.start()` and `.stop()` methods?

**Comment by Marak** [comment]
Based on the conversations I was having with Substack, the reasoning behind multiple processes is actually pretty solid. He could explain it a lot better then I could. 

For now, this ticket is flawed in its current state since a dnode / multiprocess refactor would be separate from the actor based plugin refactor. I'll come back to this issue shortly and make some edits / split it up into a few smaller tasks.

**Comment by chapel** [comment]
The point of using dnode and a process plugin system is so that plugins can be restarted, or added on the fly easily. If there is an update to a plugin, the bot doesn't have to be taken down. Also allows for more intensive plugins to be separate from the main process, so the bot is more functional even with a lot of things going on.

**Comment by Marak** [comment]
Can I summon @SubStack to the thread?

**Comment by ghost** [comment]
The more you can update the code without spamming channels the faster you can fix bugs and iteratively improve features. If you just expose the irc handle and events then processes can hook onto those and if they die it doesn't require any special sandboxing, the connection will just drop between the plugin and the main bot process and you can look at what broke. Plus with the process-oriented approach it's really easy to set up notifications for backend systems: just connect to the designated port, post a message to a channel, and exit.

**Comment by jfhbrook** [comment]
I had a similar experience with lulzbot, the irc bot I wrote, and a precursor to #stackvm's rowbit. However, I had only one connecting process that handled multiple modules to do intelligent things, instead of each module having its own process. I think this "multi-concern process" model might be appropriate for very similar concerns such as call/response behaviors, like my old !weather module and the !ddg module I had in the works (but never got around to finishing). However, I would probably split some of the other routines, such as the github-watching module I've written previously and the twitter module used in Kohai.

**Comment by jfhbrook** [comment]
Also, if you were to pipe the dnode protocol over zmq or some such you could make your system do potentially lighter-weight ipc's instead of full-on tcp networking. The way that dnode is written right now, I don't think this is too big a stretch for a future pull request.

**Comment by chapel** [comment]
@jesusabdullah I had a similar idea that I expressed to @avianflu 

I agree that you should be able to group plugins onto processes, as they make sense. So there could be a general plugin process, and then individual plugins could specify in a config or in their code that they need their own process. Could also have plugins be on demand, and only run when called.

**Comment by jfhbrook** [comment]
One last comment: If you guys are considering such a refactor you may be interested in checking out [the code for rowbit](https://github.com/substack/rowbit) which basically exposes the meat of the irc module's internal methods over dnode, given a successful auth step. It might actually be pretty close to what you're looking for as-is, at least for the irc side of things.

**Comment by Marak** [comment]
New plugin system is going to be built using hook.io. 

Once we have completed the individual hooks for each of kohai's existing i/o responsibilities, we'll push this refactor forward. Closing for now...
